# Site settings
title: Luis Gomez (whoislewys)
description: Luis 'Lewys' Gomez Personal Portfolio
baseurl: ""
url: "http://localhost:3000"

# User settings
username: Luis Gomez
user_description: Machine Learning, Creative Coding, and interactive sound are what I do best.
user_title: Computer Science Student
email: whoislewys@gmail.com
twitter_username: lorem_ipsum
github_username:  whoislewys
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
